### PR TITLE
Update graphical_sim.py

### PR DESCRIPTION
**Pull request by NiksheyYadav**
Done!!!

### CODE REVIEW

**Comment by tusharhero** [comment]
This is for #13 right?

**Comment by tusharhero** [comment]
I don't see how this change makes it clearer. I think its inconsistent. Can you clarify what you want to do?

**Comment by NiksheyYadav** [comment]
Yes

**Comment by tusharhero** [comment]
https://github.com/tusharhero/darwinio/blob/abd1fe1855e3ef025b029e3f014006c2f333171d/src/darwinio/graphical_sim.py#L270 
@NiksheyYadav  I think you want to edit these labels?

**Comment by NiksheyYadav** [comment]
Yes

**Comment by NiksheyYadav** [comment]
> https://github.com/tusharhero/darwinio/blob/abd1fe1855e3ef025b029e3f014006c2f333171d/src/darwinio/graphical_sim.py#L270 
> @NiksheyYadav  I think you want to edit these labels?

Yes, i want to change the text in the slider( where it was written food min & food Max)

**Comment by tusharhero** [comment]
Then change it :D, make another commit.

**Pull request closed without merging**
