### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by ashirbadsahu**
'pacman -S pipx' should be 'pacman -S python-pipx' and also there's a space after pipx you wrote which can cause error

### CODE REVIEW

**Comment by valium007** [comment]
good morning sirs @tusharhero @ashirbadsahu

**Review by tusharhero — APPROVED** [review]
looks good.

**Comment by ashirbadsahu** [comment]
> good morning sirs @tusharhero @ashirbadsahu

go study @Valium007

**Comment by tusharhero** [comment]
Good night @Valium007 sirs.

**Comment by NiksheyYadav** [comment]
Hello

**Comment by tusharhero** [comment]
No chatting here please.

**Pull request merged**
